name: recipes_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.2.43

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Configuração de fontes
  fonts:
    - family: Sedan
      fonts:
        - asset: assets/fonts/Sedan/Sedan-Italic.ttf
        - asset: assets/fonts/Sedan/Sedan-Regular.ttf
    - family: SedanSC
      fonts:
        - asset: assets/fonts/SedanSc/SedanSC-Regular.ttf    

  # Configuração de assets
  assets:
    - assets/images/
