# Use a imagem oficial do Node.js como base
FROM node:18

# Define o diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Copia o arquivo package.json e package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instala as dependências do projeto
RUN npm install

# Copia o restante dos arquivos do projeto para o diretório de trabalho
COPY . .

# Define a variável de ambiente para o ambiente de produção
ENV NODE_ENV=production

# Expõe a porta 3000 para o container
EXPOSE 3000

# Comando para iniciar o servidor
CMD ["node", "app.js"]
