version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # api:
  #   build: .
  #   container_name: recipe-api
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017/recipe_db
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     - mongo

volumes:
  mongo_data:
